#
# This is a sample Pomerium (https://pomerium.com) configuration file for integrating with the Model Context Protocol (MCP) servers and clients.
#

# acquire TLS certificates automatically from Let's Encrypt
autocert: true

#
# Pomerium needs to store data in a database to manage sessions, policies, and other stateful information.
#
databroker_storage_type: postgres
databroker_storage_connection_string: postgresql://postgres:postgres@postgres:5432/pomerium?sslmode=disable

# Enable MCP support
runtime_flags:
  mcp: true

# Configure routes. Change YOUR-DOMAIN to a valid domain you control.
#
routes:
  - name: Notion
    from: https://notion.YOUR-DOMAIN
    to: http://mcp-servers:8080/notion
    mcp:
      upstream_oauth2:
        # ** REPLACE WITH YOUR CLIENT ID AND SECRET **
        # SEE ./notion/README.md FOR DETAILS
        client_id: xxx
        client_secret: yyy
        # --------
        scopes: ["read:user", "user:email"]
        endpoint:
          auth_url:  "https://api.notion.com/v1/oauth/authorize"
          token_url: "https://api.notion.com/v1/oauth/token"
    policy:
      - allow:
          or:
            - domain:
                is: YOUR-DOMAIN
