name: Docker
permissions:
  contents: read
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-22.04
    outputs:
      sha-tag: ${{ steps.metadata.outputs.sha-tag }}
      image: ${{ steps.metadata.outputs.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2

      - name: Login to DockerHub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare Image Metadata
        id: metadata
        run: |
          IMAGE=pomerium/mcp-servers
          SHA_TAG=git-${GITHUB_SHA::8}
          TAGS=${IMAGE}:main
          TAGS=${TAGS},${IMAGE}:${SHA_TAG}
          TS=$(date +%Y%m%d%H%M%S)
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "timestamp=${TS}" >> $GITHUB_OUTPUT
          echo "name=pomerium-mcp-app-demo" >> $GITHUB_OUTPUT
          echo "image=${IMAGE}" >> $GITHUB_OUTPUT
          echo "sha-tag=${SHA_TAG}" >> $GITHUB_OUTPUT

      - name: Docker Publish - Main
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.metadata.outputs.tags }}
          labels: |
            org.opencontainers.image.created=${{ steps.metadata.outputs.timestamp }}
            org.opencontainers.image.name=${{ steps.metadata.outputs.name }}
            org.opencontainers.image.revision=${{ github.sha }}
